<%--
  Created by IntelliJ IDEA.
  User: intelligrape
  Date: 27/6/14
  Time: 4:16 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="studyRoom"/>
    <title></title>
</head>

<body>
<div class="hl-head">
    <h3>Collinearity , Centroid &amp; Midpoint</h3>
</div>

<div id="TabbedPannel" class="panel-container">
    <span id="1-Tab" class="active" onclick="tabbedPanelControlFn('1');">Concepts</span>
    <span id="2-Tab" class="inactive" onclick="tabbedPanelControlFn('2');">Examples</span>
    <acronym title="Enter Fullscreen" class="tabbed-panel-maximize" onclick="fullscreenToggle();"></acronym>
</div>


<%int div=0; %>


<div id="<%=++div %>-Container" class="block">
    <p></p>

    <p>Three given Points P,Q,R are said to be collinear if and only if all three points lie on a straight line.</p>
    <div class="hl-note">
        <p><b>Check Collinearity of Three Points</b></p>
        <p>Three Points are collinear if they follow either of the three following conditions</p>
        <ol>
            <li>If the area of the triangle PQR is zero.</li>
            <li>If the slope PQ = slope QR = slope QP</li>
            <li>If distance between PQ + QR = distance between PR</li>
        </ol>
    </div>
    <p></p>

    <p>
        Centroid of a triangle is a point inside the triangle such that is formed by joining all the medians of a triangle.
    </p>
    <div class="hl-note">
        <p><b>Finding Centroid Of Triangle</b></p>
        <p>
            If P(x<sub>1</sub>,y<sub>1</sub>), Q(x<sub>2</sub>,y<sub>2</sub>) and R(x<sub>3</sub>,y<sub>3</sub>) are the vertices of a triangle , then the co ordinates of
        its centroid are
            <br><br><span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(\frac{x_1+x_2+x_3}{3},\frac{y_1+y_2+y_3}{3}\right)$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1.2, 2.216666666666667);">(</span><span class="non-leaf" mathquill-block-id="29"><span class="fraction non-leaf" mathquill-command-id="4"><span class="numerator" mathquill-block-id="6"><var mathquill-command-id="5">x</var><sub class="non-leaf" mathquill-command-id="7" mathquill-block-id="9"><span mathquill-command-id="8">1</span></sub><span mathquill-command-id="11" class="binary-operator">+</span><var mathquill-command-id="13">x</var><sub class="non-leaf" mathquill-command-id="15" mathquill-block-id="17"><span mathquill-command-id="16">2</span></sub><span mathquill-command-id="19" class="binary-operator">+</span><var mathquill-command-id="21">x</var><sub class="non-leaf" mathquill-command-id="23" mathquill-block-id="25"><span mathquill-command-id="24">3</span></sub></span><span class="denominator" mathquill-block-id="28"><span mathquill-command-id="27">3</span></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="30">,</span><span class="fraction non-leaf" mathquill-command-id="32"><span class="numerator" mathquill-block-id="34"><var mathquill-command-id="33">y</var><sub class="non-leaf" mathquill-command-id="35" mathquill-block-id="37"><span mathquill-command-id="36">1</span></sub><span mathquill-command-id="39" class="binary-operator">+</span><var mathquill-command-id="41">y</var><sub class="non-leaf" mathquill-command-id="43" mathquill-block-id="45"><span mathquill-command-id="44">2</span></sub><span mathquill-command-id="47" class="binary-operator">+</span><var mathquill-command-id="49">y</var><sub class="non-leaf" mathquill-command-id="51" mathquill-block-id="53"><span mathquill-command-id="52">3</span></sub></span><span class="denominator" mathquill-block-id="56"><span mathquill-command-id="55">3</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span><span class="scaled paren" style="-webkit-transform: scale(1.2, 2.216666666666667);">)</span></span></span>
        </p>
    </div>

    <p></p>

    <div class="hl-note">
        <p><b>Finding Incenter Of A Triangle</b></p>
        If <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$A\left(x_1,y_1\right),B\left(x_2,y_2\right)$</span><var mathquill-command-id="2">A</var><span class="non-leaf" mathquill-command-id="5"><span class="scaled paren" style="-webkit-transform: scale(1.0666666666666667, 1.4);">(</span><span class="non-leaf" mathquill-block-id="7"><var mathquill-command-id="6">x</var><sub class="non-leaf" mathquill-command-id="8" mathquill-block-id="10"><span mathquill-command-id="9">1</span></sub><span mathquill-command-id="12">,</span><var mathquill-command-id="14">y</var><sub class="non-leaf" mathquill-command-id="16" mathquill-block-id="18"><span mathquill-command-id="17">1</span></sub></span><span class="scaled paren" style="-webkit-transform: scale(1.0666666666666667, 1.4);">)</span></span><span mathquill-command-id="22">,</span><var mathquill-command-id="24">B</var><span class="non-leaf" mathquill-command-id="27"><span class="scaled paren" style="-webkit-transform: scale(1.0666666666666667, 1.4);">(</span><span class="non-leaf" mathquill-block-id="29"><var mathquill-command-id="28">x</var><sub class="non-leaf" mathquill-command-id="30" mathquill-block-id="32"><span mathquill-command-id="31">2</span></sub><span mathquill-command-id="34">,</span><var mathquill-command-id="36">y</var><sub class="non-leaf" mathquill-command-id="38" mathquill-block-id="40"><span mathquill-command-id="39">2</span></sub></span><span class="scaled paren" style="-webkit-transform: scale(1.0666666666666667, 1.4);">)</span></span></span> and <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\mathbb{C}\left(x_3,y_3\right)$</span><span mathquill-command-id="2">C</span><span class="non-leaf" mathquill-command-id="5"><span class="scaled paren" style="-webkit-transform: scale(1.0666666666666667, 1.4);">(</span><span class="non-leaf" mathquill-block-id="7"><var mathquill-command-id="6">x</var><sub class="non-leaf" mathquill-command-id="8" mathquill-block-id="10"><span mathquill-command-id="9">3</span></sub><span mathquill-command-id="12">,</span><var mathquill-command-id="14">y</var><sub class="non-leaf" mathquill-command-id="16" mathquill-block-id="18"><span mathquill-command-id="17">3</span></sub></span><span class="scaled paren" style="-webkit-transform: scale(1.0666666666666667, 1.4);">)</span></span></span>
        are the vertices of a triangle ABC such that BC=a, CA=b and AB=c, then the coordinates of the incenter are given by the formulae,
        <br><br>
        I(x,y) = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(\frac{ax_1+bx_2+cx_3}{a+b+c},\frac{ay_1+by_2+cy_3}{a+b+c}\right)$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1.2, 2.216666666666667);">(</span><span class="non-leaf" mathquill-block-id="43"><span class="fraction non-leaf" mathquill-command-id="4"><span class="numerator" mathquill-block-id="6"><var mathquill-command-id="5">a</var><var mathquill-command-id="7">x</var><sub class="non-leaf" mathquill-command-id="9" mathquill-block-id="11"><span mathquill-command-id="10">1</span></sub><span mathquill-command-id="13" class="binary-operator">+</span><var mathquill-command-id="15">b</var><var mathquill-command-id="17">x</var><sub class="non-leaf" mathquill-command-id="19" mathquill-block-id="21"><span mathquill-command-id="20">2</span></sub><span mathquill-command-id="23" class="binary-operator">+</span><var mathquill-command-id="25">c</var><var mathquill-command-id="27">x</var><sub class="non-leaf" mathquill-command-id="29" mathquill-block-id="31"><span mathquill-command-id="30">3</span></sub></span><span class="denominator" mathquill-block-id="34"><var mathquill-command-id="33">a</var><span mathquill-command-id="35" class="binary-operator">+</span><var mathquill-command-id="37">b</var><span mathquill-command-id="39" class="binary-operator">+</span><var mathquill-command-id="41">c</var></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="44">,</span><span class="fraction non-leaf" mathquill-command-id="46"><span class="numerator" mathquill-block-id="48"><var mathquill-command-id="47">a</var><var mathquill-command-id="49">y</var><sub class="non-leaf" mathquill-command-id="51" mathquill-block-id="53"><span mathquill-command-id="52">1</span></sub><span mathquill-command-id="55" class="binary-operator">+</span><var mathquill-command-id="57">b</var><var mathquill-command-id="59">y</var><sub class="non-leaf" mathquill-command-id="61" mathquill-block-id="63"><span mathquill-command-id="62">2</span></sub><span mathquill-command-id="65" class="binary-operator">+</span><var mathquill-command-id="67">c</var><var mathquill-command-id="69">y</var><sub class="non-leaf" mathquill-command-id="71" mathquill-block-id="73"><span mathquill-command-id="72">3</span></sub></span><span class="denominator" mathquill-block-id="76"><var mathquill-command-id="75">a</var><span mathquill-command-id="77" class="binary-operator">+</span><var mathquill-command-id="79">b</var><span mathquill-command-id="81" class="binary-operator">+</span><var mathquill-command-id="83">c</var></span><span style="display:inline-block;width:0">&nbsp;</span></span></span><span class="scaled paren" style="-webkit-transform: scale(1.2, 2.216666666666667);">)</span></span></span>
    </div>

    <p></p>

    <div class="hl-note">
        <p><b>Mid Point Of Two Points </b></p>
        If P(x<sub>1</sub>,y<sub>1</sub>) and Q(x<sub>2</sub>,y<sub>2</sub>) are the two points, then the coordinates of point M(x<sub>mid</sub>,y<sub>mid</sub>) such
    that M is equidistant from both P and Q is given by the formulae,
        <br><br>
        M(x<sub>mid</sub>,y<sub>mid</sub>) = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(\frac{x_1+x_2}{2},\frac{y_1+y_2}{2}\right)$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1.2, 2.216666666666667);">(</span><span class="non-leaf" mathquill-block-id="21"><span class="fraction non-leaf" mathquill-command-id="4"><span class="numerator" mathquill-block-id="6"><var mathquill-command-id="5">x</var><sub class="non-leaf" mathquill-command-id="7" mathquill-block-id="9"><span mathquill-command-id="8">1</span></sub><span mathquill-command-id="11" class="binary-operator">+</span><var mathquill-command-id="13">x</var><sub class="non-leaf" mathquill-command-id="15" mathquill-block-id="17"><span mathquill-command-id="16">2</span></sub></span><span class="denominator" mathquill-block-id="20"><span mathquill-command-id="19">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="22">,</span><span class="fraction non-leaf" mathquill-command-id="24"><span class="numerator" mathquill-block-id="26"><var mathquill-command-id="25">y</var><sub class="non-leaf" mathquill-command-id="27" mathquill-block-id="29"><span mathquill-command-id="28">1</span></sub><span mathquill-command-id="31" class="binary-operator">+</span><var mathquill-command-id="33">y</var><sub class="non-leaf" mathquill-command-id="35" mathquill-block-id="37"><span mathquill-command-id="36">2</span></sub></span><span class="denominator" mathquill-block-id="40"><span mathquill-command-id="39">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span><span class="scaled paren" style="-webkit-transform: scale(1.2, 2.216666666666667);">)</span></span></span>
    </div>

</div>
<!-- ****************************************************************************************************************************** -->

<%int i=0; %>

<div id='<%=++div%>-Container' class='hidden'>


    <div class="hl-ques">
        <p><b>Example <%=++i%>.</b> Check if the points (&minus;1,&minus;1),(1,2) and (3,5) are collinear.

    </div>
    <p><input type="button" class="ans-show" id="aux<%=i %>" onclick="visibilityControl(<%=i %>);" value="Solution"></p>
    <div id="sol<%=i %>" class="hidden">
        <ul>
            <li><p>
                <b> Method 1 : </b>
                <table cellpadding="5px" border="0">
                    <tr>
                        <td>Area of &#9651; = </td><td><span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\frac{1}{2}$</span><span class="fraction non-leaf" mathquill-command-id="2"><span class="numerator" mathquill-block-id="4"><span mathquill-command-id="3">1</span></span><span class="denominator" mathquill-block-id="6"><span mathquill-command-id="5">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span></td>
                        <td><img src="/images/quants/coordinate-geometry/collinear-ex1.gif"></td>
                    </tr>
                </table>
                Area = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\frac{1}{2}$</span><span class="fraction non-leaf" mathquill-command-id="2"><span class="numerator" mathquill-block-id="4"><span mathquill-command-id="3">1</span></span><span class="denominator" mathquill-block-id="6"><span mathquill-command-id="5">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span>
                [1(&minus;1&minus;5) + 1(2&minus;5) + 3(2+1)]
                <br><br> = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\frac{1}{2}$</span><span class="fraction non-leaf" mathquill-command-id="2"><span class="numerator" mathquill-block-id="4"><span mathquill-command-id="3">1</span></span><span class="denominator" mathquill-block-id="6"><span mathquill-command-id="5">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span>[&minus;6 &minus;3 + 9]
                <br><br>= 0
                <br><br>&there4; The three points are collinear since the area is 0
            </li>
            <li><p><b>Method 2 :</b></p>
                Distance between (&minus;1,&minus;1) and (1,2) = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\sqrt{\left(-1-1\right)^2+\left(-1-2\right)^2}=\sqrt{4+9}=\sqrt{13}$</span><span class="non-leaf" mathquill-command-id="2"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 1.2888888888888888);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="14"><span class="non-leaf" mathquill-command-id="4"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="6"><span mathquill-command-id="5" class="">&minus;</span><span mathquill-command-id="7">1</span><span mathquill-command-id="9" class="binary-operator">&minus;</span><span mathquill-command-id="11">1</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="15" mathquill-block-id="17"><span mathquill-command-id="16">2</span></sup><span mathquill-command-id="19" class="binary-operator">+</span><span class="non-leaf" mathquill-command-id="22"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="24"><span mathquill-command-id="23" class="">&minus;</span><span mathquill-command-id="25">1</span><span mathquill-command-id="27" class="binary-operator">&minus;</span><span mathquill-command-id="29">2</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="33" mathquill-block-id="35"><span mathquill-command-id="34">2</span></sup></span></span><span class="binary-operator" mathquill-command-id="38">=</span><span class="non-leaf" mathquill-command-id="40"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="42"><span mathquill-command-id="41">4</span><span mathquill-command-id="43" class="binary-operator">+</span><span mathquill-command-id="45">9</span></span></span><span class="binary-operator" mathquill-command-id="48">=</span><span class="non-leaf" mathquill-command-id="50"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="52"><span mathquill-command-id="51">1</span><span mathquill-command-id="53">3</span></span></span></span>
                <br><br>Distance between (&minus;1,&minus;1) and (3,5) = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\sqrt{\left(-1-3\right)^2+\left(-1-5\right)^2}=\sqrt{16+36}=2\sqrt{13}$</span><span class="non-leaf" mathquill-command-id="2"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 1.2888888888888888);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="14"><span class="non-leaf" mathquill-command-id="4"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="6"><span mathquill-command-id="5" class="">&minus;</span><span mathquill-command-id="7">1</span><span mathquill-command-id="9" class="binary-operator">&minus;</span><span mathquill-command-id="11">3</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="15" mathquill-block-id="17"><span mathquill-command-id="16">2</span></sup><span mathquill-command-id="19" class="binary-operator">+</span><span class="non-leaf" mathquill-command-id="22"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="24"><span mathquill-command-id="23" class="">&minus;</span><span mathquill-command-id="25">1</span><span mathquill-command-id="27" class="binary-operator">&minus;</span><span mathquill-command-id="29">5</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="33" mathquill-block-id="35"><span mathquill-command-id="34">2</span></sup></span></span><span class="binary-operator" mathquill-command-id="38">=</span><span class="non-leaf" mathquill-command-id="40"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="42"><span mathquill-command-id="41">1</span><span mathquill-command-id="43">6</span><span mathquill-command-id="45" class="binary-operator">+</span><span mathquill-command-id="47">3</span><span mathquill-command-id="49">6</span></span></span><span class="binary-operator" mathquill-command-id="52">=</span><span mathquill-command-id="54">2</span><span class="non-leaf" mathquill-command-id="56"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="58"><span mathquill-command-id="57">1</span><span mathquill-command-id="59">3</span></span></span></span>
                <br><br>Distance between (1,2) and (3,5) = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\sqrt{\left(1-3\right)^2+\left(2-5\right)^2}=\sqrt{4+9}=\sqrt{13}$</span><span class="non-leaf" mathquill-command-id="2"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 1.2888888888888888);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="12"><span class="non-leaf" mathquill-command-id="4"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="6"><span mathquill-command-id="5">1</span><span mathquill-command-id="7" class="binary-operator">&minus;</span><span mathquill-command-id="9">3</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="13" mathquill-block-id="15"><span mathquill-command-id="14">2</span></sup><span mathquill-command-id="17" class="binary-operator">+</span><span class="non-leaf" mathquill-command-id="20"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="22"><span mathquill-command-id="21">2</span><span mathquill-command-id="23" class="binary-operator">&minus;</span><span mathquill-command-id="25">5</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="29" mathquill-block-id="31"><span mathquill-command-id="30">2</span></sup></span></span><span class="binary-operator" mathquill-command-id="34">=</span><span class="non-leaf" mathquill-command-id="36"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="38"><span mathquill-command-id="37">4</span><span mathquill-command-id="39" class="binary-operator">+</span><span mathquill-command-id="41">9</span></span></span><span class="binary-operator" mathquill-command-id="44">=</span><span class="non-leaf" mathquill-command-id="46"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="48"><span mathquill-command-id="47">1</span><span mathquill-command-id="49">3</span></span></span></span>
                <br><br>Since, The Distance from (&minus;1,&minus;1) to (1,2) + Distance from (1,2) to (3,5) = Distance from (&minus;1,&minus;1) to (3,5)
                <br><br>&there4; The points are collinear

        </ul>

    </div>


    <div class="hl-ques">
        <p><b>Example <%=++i%>.</b> Find the centroid of the triangle who's coordinates are (1,1),(2,&minus;3) and (3,&minus;4)

    </div>
    <p><input type="button" class="ans-show" id="aux<%=i %>" onclick="visibilityControl(<%=i %>);" value="Solution"></p>
    <div id="sol<%=i %>" class="hidden">
        Centroid = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(\frac{1+2+3}{3},\frac{1-3-4}{3}\right)=\left(2,-2\right)$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">(</span><span class="non-leaf" mathquill-block-id="17"><span class="fraction non-leaf" mathquill-command-id="4"><span class="numerator" mathquill-block-id="6"><span mathquill-command-id="5">1</span><span mathquill-command-id="7" class="binary-operator">+</span><span mathquill-command-id="9">2</span><span mathquill-command-id="11" class="binary-operator">+</span><span mathquill-command-id="13">3</span></span><span class="denominator" mathquill-block-id="16"><span mathquill-command-id="15">3</span></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="18">,</span><span class="fraction non-leaf" mathquill-command-id="20"><span class="numerator" mathquill-block-id="22"><span mathquill-command-id="21">1</span><span mathquill-command-id="23" class="binary-operator">&minus;</span><span mathquill-command-id="25">3</span><span mathquill-command-id="27" class="binary-operator">&minus;</span><span mathquill-command-id="29">4</span></span><span class="denominator" mathquill-block-id="32"><span mathquill-command-id="31">3</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">)</span></span><span class="binary-operator" mathquill-command-id="36">=</span><span class="non-leaf" mathquill-command-id="39"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="41"><span mathquill-command-id="40">2</span><span mathquill-command-id="42">,</span><span mathquill-command-id="44" class="binary-operator">&minus;</span><span mathquill-command-id="46">2</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span></span>

    </div>




    <div class="hl-ques">
        <p><b>Example <%=++i%>.</b> Find the centroid of the triangle who's coordinates are (8,7),(8,&minus;2) and (2,&minus;2)

    </div>
    <p><input type="button" class="ans-show" id="aux<%=i %>" onclick="visibilityControl(<%=i %>);" value="Solution"></p>
    <div id="sol<%=i %>" class="hidden">
        Centroid = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(\frac{8+8+2}{3},\frac{7-2-2}{3}\right)=\left(6,1\right)$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">(</span><span class="non-leaf" mathquill-block-id="17"><span class="fraction non-leaf" mathquill-command-id="4"><span class="numerator" mathquill-block-id="6"><span mathquill-command-id="5">8</span><span mathquill-command-id="7" class="binary-operator">+</span><span mathquill-command-id="9">8</span><span mathquill-command-id="11" class="binary-operator">+</span><span mathquill-command-id="13">2</span></span><span class="denominator" mathquill-block-id="16"><span mathquill-command-id="15">3</span></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="18">,</span><span class="fraction non-leaf" mathquill-command-id="20"><span class="numerator" mathquill-block-id="22"><span mathquill-command-id="21">7</span><span mathquill-command-id="23" class="binary-operator">&minus;</span><span mathquill-command-id="25">2</span><span mathquill-command-id="27" class="binary-operator">&minus;</span><span mathquill-command-id="29">2</span></span><span class="denominator" mathquill-block-id="32"><span mathquill-command-id="31">3</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">)</span></span><span class="binary-operator" mathquill-command-id="36">=</span><span class="non-leaf" mathquill-command-id="39"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="41"><span mathquill-command-id="40">6</span><span mathquill-command-id="42">,</span><span mathquill-command-id="44">1</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span></span>

    </div>




    <div class="hl-ques">
        <p><b>Example <%=++i%>.</b> Find the mid point of a line segement who's end points are (8,2) and (&minus;1,6)

    </div>
    <p><input type="button" class="ans-show" id="aux<%=i %>" onclick="visibilityControl(<%=i %>);" value="Solution"></p>
    <div id="sol<%=i %>" class="hidden">
        Mid point = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(\frac{8-1}{2},\frac{2+6}{2}\right)=\left(\frac{7}{2},4\right)$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">(</span><span class="non-leaf" mathquill-block-id="13"><span class="fraction non-leaf" mathquill-command-id="4"><span class="numerator" mathquill-block-id="6"><span mathquill-command-id="5">8</span><span mathquill-command-id="7" class="binary-operator">&minus;</span><span mathquill-command-id="9">1</span></span><span class="denominator" mathquill-block-id="12"><span mathquill-command-id="11">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="14">,</span><span class="fraction non-leaf" mathquill-command-id="16"><span class="numerator" mathquill-block-id="18"><span mathquill-command-id="17">2</span><span mathquill-command-id="19" class="binary-operator">+</span><span mathquill-command-id="21">6</span></span><span class="denominator" mathquill-block-id="24"><span mathquill-command-id="23">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">)</span></span><span class="binary-operator" mathquill-command-id="28">=</span><span class="non-leaf" mathquill-command-id="31"><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">(</span><span class="non-leaf" mathquill-block-id="37"><span class="fraction non-leaf" mathquill-command-id="32"><span class="numerator" mathquill-block-id="34"><span mathquill-command-id="33">7</span></span><span class="denominator" mathquill-block-id="36"><span mathquill-command-id="35">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="38">,</span><span mathquill-command-id="40">4</span></span><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">)</span></span></span>

    </div>


    <div class="hl-ques">
        <p><b>Example <%=++i%>.</b> Find the cordinates of the point that is equidistant from the points (&minus;5,&minus;2) and (&minus;1,8)

    </div>
    <p><input type="button" class="ans-show" id="aux<%=i %>" onclick="visibilityControl(<%=i %>);" value="Solution"></p>
    <div id="sol<%=i %>" class="hidden">
        Mid point = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(\frac{-5-1}{2},\frac{-2+8}{2}\right)=\left(-3,3\right)$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">(</span><span class="non-leaf" mathquill-block-id="15"><span class="fraction non-leaf" mathquill-command-id="4"><span class="numerator" mathquill-block-id="6"><span mathquill-command-id="5" class="">&minus;</span><span mathquill-command-id="7">5</span><span mathquill-command-id="9" class="binary-operator">&minus;</span><span mathquill-command-id="11">1</span></span><span class="denominator" mathquill-block-id="14"><span mathquill-command-id="13">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="16">,</span><span class="fraction non-leaf" mathquill-command-id="18"><span class="numerator" mathquill-block-id="20"><span mathquill-command-id="19" class="">&minus;</span><span mathquill-command-id="21">2</span><span mathquill-command-id="23" class="binary-operator">+</span><span mathquill-command-id="25">8</span></span><span class="denominator" mathquill-block-id="28"><span mathquill-command-id="27">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">)</span></span><span class="binary-operator" mathquill-command-id="32">=</span><span class="non-leaf" mathquill-command-id="35"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="37"><span mathquill-command-id="36" class="">&minus;</span><span mathquill-command-id="38">3</span><span mathquill-command-id="40">,</span><span mathquill-command-id="42">3</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span></span>

    </div>


    <div class="hl-ques">
        <p><b>Example <%=++i%>.</b> Find the distance of a point (&minus;1,&minus;3) from the mid point of a line joining the points (&minus;2, &minus;1)and (4,7)

    </div>
    <p><input type="button" class="ans-show" id="aux<%=i %>" onclick="visibilityControl(<%=i %>);" value="Solution"></p>
    <div id="sol<%=i %>" class="hidden">
        Mid point of the line = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(\frac{4-2}{2},\frac{7-1}{2}\right)=\left(1,3\right)$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">(</span><span class="non-leaf" mathquill-block-id="13"><span class="fraction non-leaf" mathquill-command-id="4"><span class="numerator" mathquill-block-id="6"><span mathquill-command-id="5">4</span><span mathquill-command-id="7" class="binary-operator">&minus;</span><span mathquill-command-id="9">2</span></span><span class="denominator" mathquill-block-id="12"><span mathquill-command-id="11">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span><span mathquill-command-id="14">,</span><span class="fraction non-leaf" mathquill-command-id="16"><span class="numerator" mathquill-block-id="18"><span mathquill-command-id="17">7</span><span mathquill-command-id="19" class="binary-operator">&minus;</span><span mathquill-command-id="21">1</span></span><span class="denominator" mathquill-block-id="24"><span mathquill-command-id="23">2</span></span><span style="display:inline-block;width:0">&nbsp;</span></span></span><span class="scaled paren" style="-webkit-transform: scale(1.1777777777777778, 1.9833333333333334);">)</span></span><span class="binary-operator" mathquill-command-id="28">=</span><span class="non-leaf" mathquill-command-id="31"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="33"><span mathquill-command-id="32">1</span><span mathquill-command-id="34">,</span><span mathquill-command-id="36">3</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span></span>
        <br><br> Distance between the point (1,3) and (&minus;1,&minus;3) = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\sqrt{\left(1+1\right)^2+\left(3+3\right)^2}=\sqrt{4+36}=2\sqrt{10}$</span><span class="non-leaf" mathquill-command-id="2"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 1.2888888888888888);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="12"><span class="non-leaf" mathquill-command-id="4"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="6"><span mathquill-command-id="5">1</span><span mathquill-command-id="7" class="binary-operator">+</span><span mathquill-command-id="9">1</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="13" mathquill-block-id="15"><span mathquill-command-id="14">2</span></sup><span mathquill-command-id="17" class="binary-operator">+</span><span class="non-leaf" mathquill-command-id="20"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="22"><span mathquill-command-id="21">3</span><span mathquill-command-id="23" class="binary-operator">+</span><span mathquill-command-id="25">3</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="29" mathquill-block-id="31"><span mathquill-command-id="30">2</span></sup></span></span><span class="binary-operator" mathquill-command-id="34">=</span><span class="non-leaf" mathquill-command-id="36"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="38"><span mathquill-command-id="37">4</span><span mathquill-command-id="39" class="binary-operator">+</span><span mathquill-command-id="41">3</span><span mathquill-command-id="43">6</span></span></span><span class="binary-operator" mathquill-command-id="46">=</span><span mathquill-command-id="48">2</span><span class="non-leaf" mathquill-command-id="50"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="52"><span mathquill-command-id="51">1</span><span mathquill-command-id="53">0</span></span></span></span>

    </div>



    <div class="hl-ques">
        <p><b>Example <%=++i%>.</b> Find the value of x such that PQ = QR, where P, Q and R are (6, &minus;1), (1, 3) and (x, 8) respectively.

    </div>
    <p><input type="button" class="ans-show" id="aux<%=i %>" onclick="visibilityControl(<%=i %>);" value="Solution"></p>
    <div id="sol<%=i %>" class="hidden">
        Distance PQ = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\sqrt{\left(6-1\right)^2+\left(-1-3\right)^2}=\sqrt{25+16}$</span><span class="non-leaf" mathquill-command-id="2"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 1.2888888888888888);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="12"><span class="non-leaf" mathquill-command-id="4"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="6"><span mathquill-command-id="5">6</span><span mathquill-command-id="7" class="binary-operator">&minus;</span><span mathquill-command-id="9">1</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="13" mathquill-block-id="15"><span mathquill-command-id="14">2</span></sup><span mathquill-command-id="17" class="binary-operator">+</span><span class="non-leaf" mathquill-command-id="20"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="22"><span mathquill-command-id="21" class="">&minus;</span><span mathquill-command-id="23">1</span><span mathquill-command-id="25" class="binary-operator">&minus;</span><span mathquill-command-id="27">3</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="31" mathquill-block-id="33"><span mathquill-command-id="32">2</span></sup></span></span><span class="binary-operator" mathquill-command-id="36">=</span><span class="non-leaf" mathquill-command-id="38"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="40"><span mathquill-command-id="39">2</span><span mathquill-command-id="41">5</span><span mathquill-command-id="43" class="binary-operator">+</span><span mathquill-command-id="45">1</span><span mathquill-command-id="47">6</span></span></span></span>
        <br><br>Distance QR = <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\sqrt{\left(x-1\right)^2+\left(8-3\right)^2}=\sqrt{\left(x-1\right)^2+25}$</span><span class="non-leaf" mathquill-command-id="2"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 1.2888888888888888);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="12"><span class="non-leaf" mathquill-command-id="4"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="6"><var mathquill-command-id="5">x</var><span mathquill-command-id="7" class="binary-operator">&minus;</span><span mathquill-command-id="9">1</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="13" mathquill-block-id="15"><span mathquill-command-id="14">2</span></sup><span mathquill-command-id="17" class="binary-operator">+</span><span class="non-leaf" mathquill-command-id="20"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="22"><span mathquill-command-id="21">8</span><span mathquill-command-id="23" class="binary-operator">&minus;</span><span mathquill-command-id="25">3</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="29" mathquill-block-id="31"><span mathquill-command-id="30">2</span></sup></span></span><span class="binary-operator" mathquill-command-id="34">=</span><span class="non-leaf" mathquill-command-id="36"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 1.2888888888888888);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="46"><span class="non-leaf" mathquill-command-id="38"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="40"><var mathquill-command-id="39">x</var><span mathquill-command-id="41" class="binary-operator">&minus;</span><span mathquill-command-id="43">1</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="47" mathquill-block-id="49"><span mathquill-command-id="48">2</span></sup><span mathquill-command-id="51" class="binary-operator">+</span><span mathquill-command-id="53">2</span><span mathquill-command-id="55">5</span></span></span></span>
        <br><br> &there4; <span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\sqrt{\left(x-1\right)^2+25}=\sqrt{25+16}$</span><span class="non-leaf" mathquill-command-id="2"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 1.2888888888888888);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="12"><span class="non-leaf" mathquill-command-id="4"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="6"><var mathquill-command-id="5">x</var><span mathquill-command-id="7" class="binary-operator">&minus;</span><span mathquill-command-id="9">1</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="13" mathquill-block-id="15"><span mathquill-command-id="14">2</span></sup><span mathquill-command-id="17" class="binary-operator">+</span><span mathquill-command-id="19">2</span><span mathquill-command-id="21">5</span></span></span><span class="binary-operator" mathquill-command-id="24">=</span><span class="non-leaf" mathquill-command-id="26"><span class="scaled sqrt-prefix" style="-webkit-transform: scale(1, 0.9);">&radic;</span><span class="non-leaf sqrt-stem" mathquill-block-id="28"><span mathquill-command-id="27">2</span><span mathquill-command-id="29">5</span><span mathquill-command-id="31" class="binary-operator">+</span><span mathquill-command-id="33">1</span><span mathquill-command-id="35">6</span></span></span></span>
        <br><br><span class="mathquill-embedded-latex mathquill-rendered-math"><span class="selectable">$\left(x-1\right)^2=16$</span><span class="non-leaf" mathquill-command-id="3"><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">(</span><span class="non-leaf" mathquill-block-id="5"><var mathquill-command-id="4">x</var><span mathquill-command-id="6" class="binary-operator">&minus;</span><span mathquill-command-id="8">1</span></span><span class="scaled paren" style="-webkit-transform: scale(1, 1.05);">)</span></span><sup class="non-leaf" mathquill-command-id="12" mathquill-block-id="14"><span mathquill-command-id="13">2</span></sup><span class="binary-operator" mathquill-command-id="16">=</span><span mathquill-command-id="18">1</span><span mathquill-command-id="20">6</span></span>
        <br><br>x<sup>2</sup> &minus;2x &minus;15 = 0 &rArr; (x&minus;5)(x+3) = 0
        <br><br>&there4; x = &minus;3 , 5

    </div>



</div>
</body>
</html>